### PR TITLE
[IMP] Add support of account-fiscal-rule, 

### PR DESCRIPTION
**Pull request by sebastienbeau**
If you install the account-fiscal-rule module the fiscal position will be updated correctly

### CODE REVIEW

**Comment by guewen** [comment]
The fiscal rules are already updated correctly in the Magento connector, can you give more information about the use case you are fixing?

**Comment by guewen** [comment]
Saw that: https://github.com/OCA/connector-magento/pull/42
I guess I was wrong and it didn't worked yet...

:+1:

**Comment by bguillot** [comment]
seems good 
:+1:

**Comment by florian-dacosta** [comment]
:+1:

**Pull request merged**
