### PR TITLE
[10.0] Add Components for connector-ecommerce

### PR DESCRIPTION
**Pull request by guewen**
Convert Units to Components, for https://github.com/OCA/connector/pull/231

The ConnectorUnits stay until 11.0

### CODE REVIEW

**Comment by guewen** [comment]
This PR is green now. Need review so we can go forward with https://github.com/OCA/connector-magento/pull/255

Worth to mention that https://github.com/OCA/connector-magento/pull/255 has been tested by several people, hence this code as well.

**Review by lmignon — APPROVED** [review]
Code review + successfully used on a custom connector.
Thank you @guewen !

**Review by dvdhinesh — APPROVED** [review]
Thanks @guewen 
Tested with custom connector. Works well. :+1:

**Review by Cedric-Pigeon — APPROVED** [review]
Code review + successfully used.
Thank you @guewen !

**Comment by guewen** [comment]
Thanks for merging!

**Pull request merged**
