### PR TITLE
Set original authors

### PR DESCRIPTION
**Pull request by guewen**
As we can now have several authors

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I feel now that "Connector Core Editors" is not needed anymore.

**Comment by guewen** [comment]
> I feel now that "Connector Core Editors" is not needed anymore.

removed

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
