### PR TITLE
[14.0][FIX] connector_ecommerce: compute should always loop

### PR DESCRIPTION
**Pull request by acsonefho**

### CODE REVIEW

**Comment by acsonefho** [comment]
@adrienpeiffer can you review this please? :)

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@OCA/connector-maintainers

**Review by guewen — APPROVED** [review]

**Review by qgroulard — APPROVED** [review]
LGTM (code review)

**Comment by acsonefho** [comment]
@OCA/connector-maintainers Can you review/merge please?
Easy one!

**Comment by simahawk** [comment]
@acsonefho next time - please - do not put the odoo version in the commit msg, thanks.

/ocabot merge patch

**Pull request merged**
