### PR TITLE
[9.0][FIX] connector_ecommerce: Add security groups to avoid show information always.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Is there any other view with the same problem?

**Comment by sergio-teruel** [comment]
I don't know.... I am sure that I will find more.. :smile:

**Comment by pedrobaeza** [comment]
Better to group all of them in the same PR

**Comment by pedrobaeza** [comment]
As general rule, all the connector pages should have this group I think

**Comment by sergio-teruel** [comment]
mhuuu, but this occours in distinct repositories... So I can't do that.
I will close this PR and later I will do a new PR with more securities improvements grouped.

**Review by cubells — APPROVED** [review]
LGTM

:+1:

**Pull request merged**
