### PR TITLE
[11.0] [MIG] connector_ecommerce

### PR DESCRIPTION
**Pull request by hugosantosred**
Depends on:

- [x] sale_automatic_workflow_payment_mode - OCA/sale-workflow#608

### CODE REVIEW

**Comment by hugosantosred** [comment]
This PR depends on https://github.com/OCA/sale-workflow/pull/608

**Comment by guewen** [comment]
Excellent! 😆 
selection_209

Code seems good from a quick eyeballing

**Review by atchuthan — APPROVED** [review]
code review :+1:

**Comment by hugosantosred** [comment]
Travis checks are green now after merging https://github.com/OCA/sale-workflow/pull/608

**Comment by pedrobaeza** [comment]
@guewen can you confirm your positive review? A side question: it's interesting to keep this repository only for this module?

**Comment by atchuthan** [comment]
@pedrobaeza @guewen Travis all green, we could merge this PR.

**Comment by pedrobaeza** [comment]
My comments haven't been answered

**Review by jaredkipe — APPROVED** [review]
Works on https://github.com/hibou-io/hibou-odoo-suite/tree/11.0/connector_walmart

**Review by guewen — APPROVED** [review]

**Comment by guewen** [comment]
> A side question: it's interesting to keep this repository only for this module?

It's not meant to and not only used by the Magento connector

**Pull request merged**
