### PR TITLE
Forward port of 7.0 up to 641ee3c

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I have this module already migrated and I'm going to propose here, but I will merge these changes.

**Comment by guewen** [comment]
@pedrobaeza could you push your branch? (and merge this one if possible)

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I merge and make a PR out of the result.

**Comment by pedrobaeza** [comment]
Here it is: https://github.com/OCA/connector-ecommerce/pull/15

**Pull request merged**
